
package com.yesmywine.logistics.rushDelivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZJSTrackingSoap", targetNamespace = "http://edi.zjs.com.rushDelivery/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZJSTrackingSoap {


    /**
     * <div style='font-family:΢���ź�; font-size:12px;'>
     *                                                         լ����������Ϣ��ѯ<br/>
     *                                                         clientFlag���ͻ���ʶ(լ�����ṩ)<br/>                                                 
     *                                                                    xml����ѯ����(ÿ�����100��)<br/>
     *                                                         verifyData��������֤��</div>
     * 
     * @param verifyData
     * @param xml
     * @param clientFlag
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get", action = "http://edi.zjs.com.rushDelivery/Get")
    @WebResult(name = "GetResult", targetNamespace = "http://edi.zjs.com.rushDelivery/")
    @RequestWrapper(localName = "Get", targetNamespace = "http://edi.zjs.com.rushDelivery/", className = "Get")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "http://edi.zjs.com.rushDelivery/", className = "GetResponse")
    public String get(
            @WebParam(name = "clientFlag", targetNamespace = "http://edi.zjs.com.rushDelivery/")
                    String clientFlag,
            @WebParam(name = "xml", targetNamespace = "http://edi.zjs.com.rushDelivery/")
                    String xml,
            @WebParam(name = "verifyData", targetNamespace = "http://edi.zjs.com.rushDelivery/")
                    String verifyData);

}
