
package com.yesmywine.logistics.vientiane;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EwinshineIntePortType", targetNamespace = "http://inte.ewin.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EwinshineIntePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://inte.ewin.com")
    @RequestWrapper(localName = "getSuccSendOrderInfo", targetNamespace = "http://inte.ewin.com", className = "GetSuccSendOrderInfo")
    @ResponseWrapper(localName = "getSuccSendOrderInfoResponse", targetNamespace = "http://inte.ewin.com", className = "GetSuccSendOrderInfoResponse")
    public String getSuccSendOrderInfo(
            @WebParam(name = "in0", targetNamespace = "http://inte.ewin.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://inte.ewin.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://inte.ewin.com")
                    String in2);

}
