
package com.yesmywine.logistics.vientiane;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EwinshineInte", targetNamespace = "http://inte.ewin.com", wsdlLocation = "http://a1inte.peitianxia.com/A1_INTE/ewinshine.Inte?wsdl")
public class EwinshineInte
    extends Service
{

    private final static URL EWINSHINEINTE_WSDL_LOCATION;
    private final static WebServiceException EWINSHINEINTE_EXCEPTION;
    private final static QName EWINSHINEINTE_QNAME = new QName("http://inte.ewin.com", "EwinshineInte");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://a1inte.peitianxia.com/A1_INTE/ewinshine.Inte?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EWINSHINEINTE_WSDL_LOCATION = url;
        EWINSHINEINTE_EXCEPTION = e;
    }

    public EwinshineInte() {
        super(__getWsdlLocation(), EWINSHINEINTE_QNAME);
    }

    public EwinshineInte(WebServiceFeature... features) {
        super(__getWsdlLocation(), EWINSHINEINTE_QNAME, features);
    }

    public EwinshineInte(URL wsdlLocation) {
        super(wsdlLocation, EWINSHINEINTE_QNAME);
    }

    public EwinshineInte(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EWINSHINEINTE_QNAME, features);
    }

    public EwinshineInte(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EwinshineInte(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EwinshineIntePortType
     */
    @WebEndpoint(name = "EwinshineInteHttpPort")
    public EwinshineIntePortType getEwinshineInteHttpPort() {
        return super.getPort(new QName("http://inte.ewin.com", "EwinshineInteHttpPort"), EwinshineIntePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EwinshineIntePortType
     */
    @WebEndpoint(name = "EwinshineInteHttpPort")
    public EwinshineIntePortType getEwinshineInteHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://inte.ewin.com", "EwinshineInteHttpPort"), EwinshineIntePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EWINSHINEINTE_EXCEPTION!= null) {
            throw EWINSHINEINTE_EXCEPTION;
        }
        return EWINSHINEINTE_WSDL_LOCATION;
    }

}
