FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD build/libs/logistics-1.0-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
